import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/NavBar";
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "Sinergia-project",
  description: "Generated by María Pilar Carranza",
  icons: [
    {
      rel: "icon",
      url: "/favicon.ico",
      sizes: "32x32",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen bg-gradient-to-r from-emerald-400 to-teal-700">
        <header className="z-10">
          <Header />
        </header>

        <main className="flex-grow">{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
